### ISSUE TITLE
Uncaught error when invalid token received

### ISSUE THREAD

**Issue by Cooryd** [libero/continuum-adaptor#17]
When hitting the `/authenticate` endpoint with an invalid token, an empty error is thrown causing lots of unwanted logger output:
```
test_continuum_auth | {"level":30,"time":1577978023114,"pid":1,"hostname":"62a94a5511ae","service":"continuum-auth","realm":"infra","msg":"GET /authenticate/SOME_TOKEN_TO_TEST {}","v":1}
test_continuum_auth | {"level":40,"time":1577978023115,"pid":1,"hostname":"62a94a5511ae","service":"continuum-auth","realm":"infra","msg":"invalidJournalJwt","v":1}
test_continuum_auth | {"level":50,"time":1577978023115,"pid":1,"hostname":"62a94a5511ae","service":"continuum-auth","realm":"domain","msg":"Invalid token","v":1}
test_continuum_auth | (node:1) UnhandledPromiseRejectionWarning: Error
test_continuum_auth |     at parsedToken.map.getOrElseL (/app/dist/use-cases/authenticate.js:27:15)
test_continuum_auth |     at TNone.getOrElseL (/app/node_modules/funfix-core/dist/umd.js:661:63)
test_continuum_auth |     at /app/dist/use-cases/authenticate.js:24:10
test_continuum_auth |     at Generator.next (<anonymous>)
test_continuum_auth |     at /app/dist/use-cases/authenticate.js:8:71
test_continuum_auth |     at new Promise (<anonymous>)
test_continuum_auth |     at __awaiter (/app/dist/use-cases/authenticate.js:4:12)
test_continuum_auth |     at funfix_1.Option.of.map (/app/dist/use-cases/authenticate.js:19:21)
test_continuum_auth |     at TSome.map (/app/node_modules/funfix-core/dist/umd.js:686:48)
test_continuum_auth |     at /app/dist/use-cases/authenticate.js:19:6
test_continuum_auth |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
test_continuum_auth |     at next (/app/node_modules/express/lib/router/route.js:137:13)
test_continuum_auth |     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
test_continuum_auth |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
test_continuum_auth |     at /app/node_modules/express/lib/router/index.js:281:22
test_continuum_auth |     at param (/app/node_modules/express/lib/router/index.js:354:14)
test_continuum_auth | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

This looks to be because of https://github.com/libero/continuum-auth/blob/b0842e4dd649ca2474ddc624e4a9456dca8acfb3/src/use-cases/authenticate.ts#L47

**Comment by erezmus** [comment]
is this still relevant? @Cooryd

**Comment by hdrury1** [comment]
Closing as error no longer uncaught on master
